import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useNavigate, useSearchParams } from 'react-router-dom';
import { Compass, ShieldCheck, MessageCircleMore, Target, CalendarDays, TrendingUp } from 'lucide-react';
import { Button } from './components/ui/button';
import { Card } from './components/ui/card';
import { Badge } from './components/ui/badge';
import './styles.css';

type FormData = { email:string; name:string; url:string; desc:string; customer:string; stage:string; goal:string; category:string; proof:string; tone:string };
type RequestData = FormData & { selectedPlan?: string; createdAt: string; campaignData: string };
const stages=['Idea','MVP','Launched','Has users','Has revenue']; const goals=['Feedback','Beta users','Traffic','Customers','Waitlist','Affiliates']; const tones=['Helpful','Honest','Founder story','Technical','Spicy'];
const sampleSubs=['r/SideProject','r/SaaS','r/micro_saas'];
const trackEvent = (eventName:string, properties:Record<string, unknown>={}) => { if (import.meta.env.DEV) console.log('[trackEvent]', eventName, properties); };
const saveRequest=(req:RequestData)=>{const arr:RequestData[]=JSON.parse(localStorage.getItem('threadscout-requests')||'[]'); arr.unshift(req); localStorage.setItem('threadscout-requests',JSON.stringify(arr.slice(0,50)));}; // temp until DB integration

const Header=()=> <header className='top'><Link to='/' className='logo'><Compass size={18}/> <b>Thread</b>Scout</Link><nav><Link to='/generate'>Generate</Link><Link to='/examples'>Examples</Link><Link to='/admin/requests'>Admin</Link></nav></header>;
const Footer=()=> <footer className='foot'><Link to='/generate'><Button>Build my Reddit campaign</Button></Link><p>ThreadScout does not auto-post, mass-DM, or connect to your Reddit account.</p></footer>;

const Landing=()=> <>
<section className='hero rail'><div><Badge className='accent'>Built for SaaS founders who want Reddit traffic without spam</Badge><h1>Launch your SaaS on Reddit without getting roasted.</h1><p>ThreadScout builds a value-first Reddit campaign for your product: the right subreddits, post angles, replies, rules, and a 7-day action plan.</p><div className='cta'><Link to='/generate'><Button>Build my campaign</Button></Link><Link to='/result'><Button variant='outline'>View example output</Button></Link></div><p className='muted'>ThreadScout does not auto-post, mass-DM, or connect to your Reddit account. It helps you plan manual, value-first campaigns.</p></div><Card className='dash'><h3>Campaign: AI Brand Tool Launch</h3><div className='metrics'>{[[Target,'Target subreddits','10'],[TrendingUp,'Post angles','12'],[MessageCircleMore,'Reply templates','20'],[ShieldCheck,'Risk score','Medium']].map(([I,k,v]:any)=><div key={k} className='mini'><I size={14}/><small>{k}</small><b>{v}</b></div>)}</div><ul>{sampleSubs.map(s=><li key={s}><b>{s}</b><Badge>Medium</Badge></li>)}</ul><p className='muted'><CalendarDays size={14}/> Day 1 post, day 2 replies, day 3 feedback thread.</p></Card></section>
<Pricing /><section className='card'><h3>Early users get manual review.</h3><p>For the first 20 paid founders, we’ll manually review your campaign and add notes before you post. This helps you avoid generic posts and choose the safest first move.</p></section>
</>;

const Generate=()=>{const nav=useNavigate(); React.useEffect(()=>trackEvent('generator_started'),[]); const [f,setF]=React.useState<FormData>(()=>JSON.parse(localStorage.getItem('threadscout-form')||'{"email":"","name":"","url":"","desc":"","customer":"","stage":"MVP","goal":"Feedback","category":"","proof":"","tone":"Helpful"}')); const save=(n:FormData)=>{setF(n); localStorage.setItem('threadscout-form',JSON.stringify(n));};
const submit=()=>{if(!f.email.trim()) return alert('Please add your email to continue.'); trackEvent('email_submitted',{email:f.email}); trackEvent('campaign_generated',{goal:f.goal}); nav('/result?'+new URLSearchParams(f as any).toString());};
return <section className='split'><form className='card form'><h1>Build your campaign</h1><label>Where should we send your campaign?<small>No spam. Just your campaign and launch notes.</small><input required type='email' value={f.email} onChange={e=>save({...f,email:e.target.value})}/></label><h3>Step 1: Product</h3><label>Product name<input value={f.name} onChange={e=>save({...f,name:e.target.value})}/></label><label>Product URL<input value={f.url} onChange={e=>save({...f,url:e.target.value})}/></label><label>What does it do?<input value={f.desc} onChange={e=>save({...f,desc:e.target.value})}/></label><h3>Step 2: Audience and goal</h3><label>Target customer<input value={f.customer} onChange={e=>save({...f,customer:e.target.value})}/></label><label>Main goal<select value={f.goal} onChange={e=>save({...f,goal:e.target.value})}>{goals.map(s=><option key={s}>{s}</option>)}</select></label><label>Product stage<select value={f.stage} onChange={e=>save({...f,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><h3>Step 3: Proof and tone</h3><label>Product category<input value={f.category} onChange={e=>save({...f,category:e.target.value})}/></label><label>Proof or milestone<input value={f.proof} onChange={e=>save({...f,proof:e.target.value})}/></label><label>Tone<select value={f.tone} onChange={e=>save({...f,tone:e.target.value})}>{tones.map(s=><option key={s}>{s}</option>)}</select></label><Button type='button' onClick={submit}>Generate free preview</Button></form><Card><h3>What you’ll get</h3><ul><li>Free preview strategy</li><li>Subreddit shortlist</li><li>Upgrade-ready full report</li></ul></Card></section>}

const Result=()=>{const [s]=useSearchParams(); const nav=useNavigate(); const product=s.get('name')||'Your SaaS'; const email=s.get('email')||''; const [plan,setPlan]=React.useState('Free');
const brief=`ThreadScout Campaign Brief\nEmail: ${email}\nProduct: ${product}\nGoal: ${s.get('goal')||'Feedback'}\nCampaign type: Founder Story + Feedback\nBest first post: Ask for teardown with one clear question\nSubreddits: ${sampleSubs.join(', ')}\n7-day plan: Day1 intro, Day2 comments, Day3 feedback thread\nSelected plan: ${plan}`;
const buy=(p:string)=>{setPlan(p); saveRequest({email,name:product,url:s.get('url')||'',desc:s.get('desc')||'',customer:s.get('customer')||'',stage:s.get('stage')||'',goal:s.get('goal')||'',category:s.get('category')||'',proof:s.get('proof')||'',tone:s.get('tone')||'',selectedPlan:p,createdAt:new Date().toISOString(),campaignData:brief}); trackEvent(p==='Launch Pack — $19'?'launch_pack_clicked':'founder_review_clicked'); nav('/checkout?plan='+encodeURIComponent(p));};
return <div className='stack'><h1>Your 7-Day Reddit Campaign</h1><Card><p>Free preview for {product}. Email: {email || 'missing'}.</p><p>Best first post: “Founder here—can I get blunt feedback before launch?”</p><p>Recommended: {sampleSubs.join(', ')}</p></Card>
<Card><h3>Want the full 7-day campaign?</h3><p>Unlock 10 subreddit targets, 3 full post drafts, 20 replies, a rules checklist, tracker, and manual review notes for early users.</p><div className='cta'><Button onClick={()=>buy('Launch Pack — $19')}>Get Launch Pack — $19</Button><Button variant='outline' onClick={()=>buy('Founder Review — $49')}>Get Founder Review — $49</Button></div><p className='muted'>ThreadScout does not auto-post, mass-DM, or connect to your Reddit account. It helps you plan manual, value-first campaigns.</p></Card>
<Card><h3>Copy campaign brief</h3><pre>{brief}</pre><Button type='button' onClick={async()=>{await navigator.clipboard.writeText(brief); trackEvent('brief_copied');}}>Copy brief</Button></Card></div>}

const Checkout=()=>{const [s]=useSearchParams(); const plan=s.get('plan')||'Launch Pack — $19'; return <Card><h1>Checkout</h1><p>Plan: {plan}</p><p>Stripe checkout coming next</p><Button disabled>Stripe checkout coming next</Button><p className='muted'>Set `VITE_STRIPE_PUBLISHABLE_KEY`, `VITE_STRIPE_PRICE_LAUNCH`, and `VITE_STRIPE_PRICE_FOUNDER` when Stripe is added.</p><Link to='/success'><Button>Mark as requested</Button></Link></Card>};
const Success=()=> <Card><h1>Your Reddit campaign request is in.</h1><p>We’ve saved your product details. If you selected a paid plan, your full campaign will include subreddit targets, post drafts, reply templates, rules, and a 7-day action plan.</p><ul><li>Check your email</li><li>Prepare your product link</li><li>Do not post the same thing across many subreddits</li><li>Start by replying helpfully before dropping links</li></ul><Link to='/generate'><Button>Generate another campaign</Button></Link></Card>;
const Admin=()=>{const reqs:RequestData[]=JSON.parse(localStorage.getItem('threadscout-requests')||'[]'); return <Card><h1>Admin requests (local demo)</h1>{reqs.length===0?<p>No requests yet.</p>:reqs.map((r,i)=><div key={i} className='mini'><b>{r.email}</b> — {r.name} — {r.selectedPlan||'Free'} — {new Date(r.createdAt).toLocaleString()}</div>)}</Card>};
const Examples=()=> <section className='grid'>{['Free Audit','Roast My Landing Page','Founder Story'].map(x=><Card key={x}><h3>{x}</h3><Link to='/generate'><Button variant='outline'>Generate similar campaign</Button></Link></Card>)}</section>;
const Pricing=()=> <section id='pricing' className='grid'><Card><h3>Launch Pack — $19</h3><Badge className='accent'>First 20 users</Badge><p>Full 7-day Reddit campaign + tracker.</p></Card><Card><h3>Founder Review — $49</h3><Badge className='accent'>First 20 users</Badge><p>Everything in Launch Pack + manual review.</p></Card><Card><p className='muted'>ThreadScout does not auto-post, mass-DM, or connect to your Reddit account.</p></Card></section>;

const App=()=> <BrowserRouter><Header/><main><Routes><Route path='/' element={<Landing/>}/><Route path='/generate' element={<Generate/>}/><Route path='/result' element={<Result/>}/><Route path='/checkout' element={<Checkout/>}/><Route path='/success' element={<Success/>}/><Route path='/admin/requests' element={<Admin/>}/><Route path='/examples' element={<Examples/>}/></Routes></main><Footer/></BrowserRouter>;
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
